### ISSUE TITLE
Regarding a missing import statement in the file "lts-candidate-stats" in bin/ folder

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/backend-commit-history-parser#15]
Just a minor observation regarding the file ` lts-candidate-stats`. If I do not have the below import statement below the shebang, the code seems to be broken when I run something like `lts-candidate-stats 2.361.2`:

```groovy
import groovy.xml.XmlSlurper;
```

Should I open a PR to update the file? I would be happy to submit one if it is useful. 

For the context, I am currently using `groovy` with the following version details:
```shell
Groovy Version: 4.0.5 JVM: 11.0.16 Vendor: Amazon.com Inc. OS: Mac OS X
```

**Comment by MarkEWaite** [comment]
Yes, please, open a PR.  If you need to modify the script to work in your environment, other release leads will likely need to modify it to work in their environments.

**Comment by krisstern** [comment]
Sure @MarkEWaite! Let me follow up with a PR now.
